// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Lovx6eVS2WNp7q8n2UmrsCbALGhTiPM',
    appId: '1:25779814206:web:0b80384782b7912348f66f',
    messagingSenderId: '25779814206',
    projectId: 'jphack2024',
    authDomain: 'jphack2024.firebaseapp.com',
    storageBucket: 'jphack2024.appspot.com',
    measurementId: 'G-KNSE3V56SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMH4WJRGxeCk5VABZBVshqiBysiHgLklQ',
    appId: '1:25779814206:android:4a8d0d480231a5b348f66f',
    messagingSenderId: '25779814206',
    projectId: 'jphack2024',
    storageBucket: 'jphack2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBC9lRzhtz9ZKkz17gUkZ3KV_TVfq6Do8',
    appId: '1:25779814206:ios:277a57236d6252ec48f66f',
    messagingSenderId: '25779814206',
    projectId: 'jphack2024',
    storageBucket: 'jphack2024.appspot.com',
    iosBundleId: 'com.example.ekiKuguru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBC9lRzhtz9ZKkz17gUkZ3KV_TVfq6Do8',
    appId: '1:25779814206:ios:277a57236d6252ec48f66f',
    messagingSenderId: '25779814206',
    projectId: 'jphack2024',
    storageBucket: 'jphack2024.appspot.com',
    iosBundleId: 'com.example.ekiKuguru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Lovx6eVS2WNp7q8n2UmrsCbALGhTiPM',
    appId: '1:25779814206:web:3dfd31924337cb0048f66f',
    messagingSenderId: '25779814206',
    projectId: 'jphack2024',
    authDomain: 'jphack2024.firebaseapp.com',
    storageBucket: 'jphack2024.appspot.com',
    measurementId: 'G-F8563JZ8P4',
  );

}